// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAvPze-paX60eUXpR_AfnNBc7059jxPTYA',
    appId: '1:167871417806:web:3d54644c7aedc1cd69af9f',
    messagingSenderId: '167871417806',
    projectId: 'app-pokedex-7f186',
    authDomain: 'app-pokedex-7f186.firebaseapp.com',
    storageBucket: 'app-pokedex-7f186.appspot.com',
    measurementId: 'G-BXGE85CY02',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBDyqODSwOx9MSXtbOTyrhGukbbyIYoBJ0',
    appId: '1:167871417806:android:14a53f4f463f152569af9f',
    messagingSenderId: '167871417806',
    projectId: 'app-pokedex-7f186',
    storageBucket: 'app-pokedex-7f186.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBNoudDa7DPRTbPGmEKHBydIEGdLHaUsvM',
    appId: '1:167871417806:ios:d739302c769c6d2169af9f',
    messagingSenderId: '167871417806',
    projectId: 'app-pokedex-7f186',
    storageBucket: 'app-pokedex-7f186.appspot.com',
    iosBundleId: 'br.dev.yago.appPokedex',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBNoudDa7DPRTbPGmEKHBydIEGdLHaUsvM',
    appId: '1:167871417806:ios:af9c61e00a64ee6a69af9f',
    messagingSenderId: '167871417806',
    projectId: 'app-pokedex-7f186',
    storageBucket: 'app-pokedex-7f186.appspot.com',
    iosBundleId: 'br.dev.yago.appPokedex.RunnerTests',
  );
}
